Fix prefetch_factor incompatibility with num_workers=0
When using PreloadedCacheDataset, we set num_workers=0 but forgot to clear
prefetch_factor, which is only valid with multiprocessing (num_workers > 0).

Error: 'prefetch_factor option could only be specified in multiprocessing'

Fix: Remove prefetch_factor from loader_kwargs when using num_workers=0.